//ff:func feature=codegen type=codegen control=sequence
//ff:what GenerateRegister — generates RegisterAll function as Go source code
package codegen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/park-jun-woo/toulmin/pkg/toulmin"
)

// GenerateRegister produces a Go source file containing RegisterAll(eng)
// that registers all given rules. The output is gofmt-formatted.
func GenerateRegister(pkgName string, metas []toulmin.RuleMeta) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by toulmin. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import \"github.com/park-jun-woo/toulmin/pkg/toulmin\"\n\n")
	buf.WriteString("func RegisterAll(eng *toulmin.Engine) {\n")
	buildRegisterBody(&buf, metas)
	buf.WriteString("}\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), err
	}
	return string(formatted), nil
}
