//ff:func feature=codegen type=codegen control=iteration dimension=1
//ff:what GenerateGraph — generates Graph Builder Go code from GraphDef
package codegen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/park-jun-woo/toulmin/internal/graphdef"
)

// GenerateGraph produces a Go source file containing a Graph Builder variable
// from a GraphDef. The output is gofmt-formatted.
func GenerateGraph(pkgName string, def *graphdef.GraphDef) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by toulmin. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import \"github.com/park-jun-woo/toulmin/pkg/toulmin\"\n\n")
	varName := graphVarName(def.Graph)
	fmt.Fprintf(&buf, "var %s = toulmin.NewGraph(%q)", varName, def.Graph)
	for _, r := range def.Rules {
		method := roleToMethod(r.Role)
		fmt.Fprintf(&buf, ".\n\t%s(%s, %g)", method, r.Name, *r.Qualifier)
	}
	for _, d := range def.Defeats {
		fmt.Fprintf(&buf, ".\n\tDefeat(%s, %s)", d.From, d.To)
	}
	buf.WriteString("\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), err
	}
	return string(formatted), nil
}
