//ff:func feature=cli type=command control=sequence
//ff:what TestGenCmdTransfer — gen on the transfer fixture prints a generated-file header to stdout, and -o writes it to a file instead
package tanglcli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenCmdTransfer runs "tangl gen" against transfer.md both with no -o
// flag, checking the generated source is printed to stdout with the "Code
// generated" banner, and with an -o flag, checking the generated source is
// written to that file (and not to stdout) with the same banner.
func TestGenCmdTransfer(t *testing.T) {
	t.Run("stdout", func(t *testing.T) {
		cmd := NewRootCmd()
		var out bytes.Buffer
		cmd.SetOut(&out)
		cmd.SetArgs([]string{"gen", "../../pkg/tangl/parser/testdata/transfer.md"})
		if err := cmd.Execute(); err != nil {
			t.Fatalf("Execute: %v", err)
		}
		if !strings.Contains(out.String(), "// Code generated by tangl. DO NOT EDIT.") {
			t.Errorf("missing generated-file header; got:\n%s", out.String())
		}
		if !strings.Contains(out.String(), "package transfer") {
			t.Errorf("missing package clause; got:\n%s", out.String())
		}
	})

	t.Run("out file", func(t *testing.T) {
		outPath := filepath.Join(t.TempDir(), "transfer_gen.go")
		cmd := NewRootCmd()
		var out bytes.Buffer
		cmd.SetOut(&out)
		cmd.SetArgs([]string{"gen", "../../pkg/tangl/parser/testdata/transfer.md", "-o", outPath})
		if err := cmd.Execute(); err != nil {
			t.Fatalf("Execute: %v", err)
		}
		if out.Len() != 0 {
			t.Errorf("expected no stdout output with -o, got:\n%s", out.String())
		}
		data, err := os.ReadFile(outPath)
		if err != nil {
			t.Fatalf("ReadFile: %v", err)
		}
		if !strings.Contains(string(data), "// Code generated by tangl. DO NOT EDIT.") {
			t.Errorf("missing generated-file header in %s; got:\n%s", outPath, string(data))
		}
	})
}
