//ff:func feature=codegen type=codegen control=iteration dimension=1
//ff:what GenerateGraph — generates Graph Go code from GraphDef with rule references
package toulmin

import (
	"bytes"
	"fmt"
	"go/format"
)

// GenerateGraph produces a Go source file containing a Graph variable
// from a GraphDef. Uses rule references (no chaining). Output is gofmt-formatted.
func GenerateGraph(pkgName string, def *GraphDef) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by toulmin. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import \"github.com/park-jun-woo/toulmin/pkg/toulmin\"\n\n")
	varName := graphVarName(def.Graph)
	fmt.Fprintf(&buf, "var %s = func() *toulmin.Graph {\n", varName)
	fmt.Fprintf(&buf, "\tg := toulmin.NewGraph(%q)\n", def.Graph)

	varNames := make(map[string]string)
	for _, r := range def.Rules {
		method := roleToMethod(r.Role)
		goVar := ruleVarName(r.Name)
		varNames[r.Name] = goVar
		fmt.Fprintf(&buf, "\t%s := g.%s(%s, nil, %g)\n", goVar, method, r.Name, r.Qualifier)
	}

	for _, d := range def.Defeats {
		fromVar := varNames[d.From]
		toVar := varNames[d.To]
		fmt.Fprintf(&buf, "\tg.Defeat(%s, %s)\n", fromVar, toVar)
	}

	buf.WriteString("\treturn g\n")
	buf.WriteString("}()\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), err
	}
	return string(formatted), nil
}
